Note: 

Both SwapRateMCSimulator and SwapRatePCAEstimator require historical swap rate time series data in a specific format.
If no explicit file path is provided to the constructor, a default CSV file will be used instead.

The default dataset is located in the "curve_data" folder of the project (see "eur_swap_ts.csv" for the expected format).

In the examples below, a file path is explicitly provided, although it points to the same data as the default.

This notebook demonstrates how to:
- create hedges and hedged liability portfolios based on original liability position

In [1]:
from __future__ import annotations
import os 
from pathlib import Path

# It is assumed that the notebook is executed from within the project - either root or sub folder. 
CWD_PATH = Path.cwd()
SWAP_TIME_SERIES_CSV_PATH = ""

for parent in CWD_PATH.parents:
 if (parent / "src").exists():
     SWAP_TIME_SERIES_CSV_PATH = parent / "curve_data" / "eur_swap_ts.csv"
     break       
 else:
     SWAP_TIME_SERIES_CSV_PATH = CWD_PATH / "curve_data" / "eur_swap_ts.csv"

print(CWD_PATH)
print(SWAP_TIME_SERIES_CSV_PATH)

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\example_notebooks
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\curve_data\eur_swap_ts.csv

In [2]:
# imports 
from typing import Dict
from datetime import datetime 
import numpy as np
import pandas as pd 
from rateslib import IRS as rlIRS, dcf as rlDCF 
from curve_engine.swap_curve_solver import SwapCurveSolver
from curve_engine.swap_curve_builder import SwapCurveBuilder
from curve_engine.swap_rate_pca_estimator import SwapRatePCAEstimator
from curve_engine.swap_rate_mc_simulator import SwapRateMCSimulator
from curve_engine.swap_curve_scenario_generator import SwapCurveScenarioGenerator
from position_engine.euribor6m_irs_position import Euribor6mIRSPosition
from position_engine.liability_position import LiabilityPosition 
from position_engine.liability_portfolio import LiabilityPortfolio
from hedge_engine.liability_hedge_constructor import LiabilityHedgeConstructor

C:\Users\mduba\AppData\Local\Temp\ipykernel_23716\76073408.py:6: LicenceNotice:
Rateslib is source-available (not open-source) software distributed under a dual-licence model.
No commercial licence is registered for this installation. Use is therefore permitted for non-commercial purposes only (at-home or university based academic use).
Any use in commercial, professional, or for-profit environments, including evaluation or trial use, requires a valid commercial licence or an approved evaluation licence.
Certain features may require a registered commercial or evaluation licence in current or future versions.
For licensing information or to register a licence, please visit: https://rateslib.com/licence
  from rateslib import IRS as rlIRS, dcf as rlDCF

In [3]:
# parameters 
curve_date = datetime(2026,3,31)

swap_rates =  {
 '2Y' : 2.948 , 
 '3Y' : 2.934, 
 '5Y' : 2.983, 
 '7Y' : 3.036, 
 '10Y': 3.11,  
 '12Y': 3.195,  
 '15Y': 3.2439, 
 '20Y': 3.246, 
 '25Y': 3.186,
 '30Y': 3.115 }
 
liabilities_payment_schedule = {
 '1Y': 240716648,   '2Y': 249313671,  '3Y': 260776369,  '4Y': 275104740,   
 '5Y': 292298787,   '6Y': 312358507,  '7Y': 335283902,  '8Y': 361074972, 
 '9Y': 384000367,  '10Y': 406925762, '11Y': 395463064, '12Y': 418388459,
 '13Y': 444179529, '14Y': 472836273, '15Y': 504358691, '16Y': 535881109, 
 '17Y': 561672178, '18Y': 578866225, '19Y': 587463248, '20Y': 590328922,
 '21Y': 584597573, '22Y': 590328922, '23Y': 584597573, '24Y': 573134876,
 '25Y': 555940830, '26Y': 533015435, '27Y': 504358691, '28Y': 469970598, 
 '29Y': 429851157, '30Y': 389731716 }

In [4]:
# create a solver - enables calibration of curve to swap rates
solver = SwapCurveSolver(
 solver_id = 'eurswap_solver', 
 curve_date = curve_date, 
 instrument_rates = swap_rates
)

SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.554749889445546e-16, `time`: 0.1157s

In [5]:
# construct the curve       
curve = SwapCurveBuilder.from_solver(
 curve_id = 'eurswap', 
 curve_solver = solver
)

In [6]:
# create the par -> forward Jacobian for the curve - needed to derive forward swap rates and calculate forward PV01
curve.calc_par_fwd_jacobian()

SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0073s

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(

In [7]:
# run pca from csv file with time series data for swap rates
swap_rate_pca = SwapRatePCAEstimator.from_csv( 
 swap_ts_csv_path = SWAP_TIME_SERIES_CSV_PATH 
)

In [8]:
# run mc simulation with scenarios for market/swap rates - 1000 scenarios, 1d shocks scaled to 30 day horizon
swap_rate_sim = SwapRateMCSimulator.from_csv(
  n_scenarios = 1000, 
  t_scale_factor = 30, 
  rng_seed = 1, 
  swap_ts_csv_path = SWAP_TIME_SERIES_CSV_PATH 
)

In [9]:
# create scenarios for curves calibrated to mc simulated market/swap rates 
scenarios = SwapCurveScenarioGenerator( 
    curve_date = curve_date, 
    swap_rate_sim = swap_rate_sim, 
    swap_rate_pca = swap_rate_pca
)

In [10]:
# calibrate the curves in each scenario of swap rates - required to generate PnL scenarios for mc CVaR calculation
# Note! For 1000 scenarios, this takes approx. 5-6 mins. 
scenarios.build_mc_scenario_curves( curve_id = 'eurswap' )

SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.13574640726366e-16, `time`: 0.0916s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.50531716466949e-16, `time`: 0.0934s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.137182868220651e-16, `time`: 0.1011s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.6703745712172888e-16, `time`: 0.0914s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 9.661113896766674e-16, `time`: 0.0935s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.4509528820842696e-16, `time`: 0.0917s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.586365078553314e-16, `time`: 0.0958s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.474079273925337e-16, `time`: 0.0923s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.579232650938731e-16, `time`: 0.0966s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.56787004849435e-16, `time`: 0.0919s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.1133737520284806e-16, `time`: 0.0943s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.90186609302717e-16, `time`: 0.0942s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.301719472756319e-16, `time`: 0.1025s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.851438160455768e-16, `time`: 0.1240s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.83291581434922e-16, `time`: 0.0941s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.052105084176452e-16, `time`: 0.0915s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.780332905743581e-16, `time`: 0.0945s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.411736188513397e-16, `time`: 0.0906s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.287779883505857e-16, `time`: 0.0949s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.566103877493744e-16, `time`: 0.0920s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.7802181736384122e-16, `time`: 0.0950s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.714396318733685e-16, `time`: 0.0916s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.601709982571955e-16, `time`: 0.1032s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.285817151034482e-16, `time`: 0.0971s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.356883621471978e-16, `time`: 0.0973s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.147516140766904e-16, `time`: 0.1281s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.3695443244597673e-15, `time`: 0.1039s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 9.90248348546396e-16, `time`: 0.0912s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.6104829858097e-16, `time`: 0.0986s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.111984327066024e-16, `time`: 0.1152s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.648896709783334e-16, `time`: 0.1362s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.580211783919314e-16, `time`: 0.1182s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 9.182933166235002e-16, `time`: 0.1299s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.6696552957848943e-16, `time`: 0.1317s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.1565384873025453e-15, `time`: 0.1311s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.2032450197944077e-16, `time`: 0.1452s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.645208877125993e-16, `time`: 0.1582s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.805633071671916e-16, `time`: 0.1006s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.391522877147711e-16, `time`: 0.0949s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.1339641484134136e-16, `time`: 0.0927s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.801569646415613e-16, `time`: 0.0947s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.8637260581525666e-15, `time`: 0.0922s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.1800432972293657e-16, `time`: 0.0949s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.637319155853244e-16, `time`: 0.0924s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.4139504384504477e-16, `time`: 0.1087s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.2950617506597007e-16, `time`: 0.0943s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.220120784464554e-16, `time`: 0.0951s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.602461704795261e-16, `time`: 0.0910s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.604339910361694e-16, `time`: 0.0927s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.342770271096582e-16, `time`: 0.0941s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.413636924209334e-15, `time`: 0.1098s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.225983047080911e-16, `time`: 0.1022s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.669847664875345e-16, `time`: 0.1033s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.763286381836591e-16, `time`: 0.0927s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.748316135796873e-16, `time`: 0.0975s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.90761005397867e-16, `time`: 0.0943s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.318588111699936e-16, `time`: 0.0984s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.2228598801731e-16, `time`: 0.0906s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.299545396138593e-16, `time`: 0.1005s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.002313575626933e-15, `time`: 0.0929s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.792963483613025e-16, `time`: 0.0922s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.2189946083765986e-16, `time`: 0.0963s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.0907450849685891e-16, `time`: 0.0957s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.118440838628137e-16, `time`: 0.0925s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.157695478175317e-16, `time`: 0.0922s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.927020073989035e-16, `time`: 0.0970s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.840061179437851e-16, `time`: 0.0926s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.3459803229558746e-15, `time`: 0.0941s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.752400151704536e-16, `time`: 0.0955s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.480158985486223e-16, `time`: 0.1046s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.91892948108552e-15, `time`: 0.0976s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.974330844970541e-16, `time`: 0.0964s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.1921021849015777e-16, `time`: 0.0903s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.578045303701128e-16, `time`: 0.0947s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.008770636367231e-16, `time`: 0.0930s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.739319460744687e-16, `time`: 0.0945s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.063265482047721e-16, `time`: 0.0966s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.3073453081290905e-16, `time`: 0.0957s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.270799625997866e-16, `time`: 0.0946s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.135327033640131e-16, `time`: 0.0995s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.668660271713552e-15, `time`: 0.1061s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.0148609976582154e-15, `time`: 0.1058s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.656381193903996e-16, `time`: 0.0983s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.697615386845859e-16, `time`: 0.0987s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.3674960425908445e-16, `time`: 0.0982s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.6085145297961996e-16, `time`: 0.0962s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.454353557476344e-17, `time`: 0.0948s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.66869812568148e-16, `time`: 0.1002s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.959491011844412e-16, `time`: 0.0943s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.871806810626199e-16, `time`: 0.0964s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.398389326907379e-16, `time`: 0.0932s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.095710296938629e-15, `time`: 0.0973s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.4208313145944795e-16, `time`: 0.1024s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.314030341041969e-16, `time`: 0.1137s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.580590370677067e-16, `time`: 0.1182s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.485490435979101e-16, `time`: 0.1060s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.668671760354484e-16, `time`: 0.1037s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.817361840053322e-16, `time`: 0.0983s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.034066355194998e-16, `time`: 0.1049s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.694463550372134e-16, `time`: 0.1247s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.073736300423774e-16, `time`: 0.0957s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.053499600722256e-15, `time`: 0.0934s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.4423262736593753e-16, `time`: 0.1007s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.0046360854349386e-16, `time`: 0.0962s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.023733413232998e-15, `time`: 0.0990s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.0118557042505542e-15, `time`: 0.0966s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.985961226239816e-16, `time`: 0.0951s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.399399239185251e-16, `time`: 0.0954s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.561998820655402e-16, `time`: 0.0955s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.560453413940866e-16, `time`: 0.0960s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.264711536311701e-16, `time`: 0.1071s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.635352697319535e-16, `time`: 0.1124s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.4934826852677856e-16, `time`: 0.1039s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.402292039262554e-16, `time`: 0.0947s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.263379085818155e-16, `time`: 0.0936s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.721467960804396e-16, `time`: 0.0915s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.26406390556403e-16, `time`: 0.0951s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.114806973884626e-15, `time`: 0.0991s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.309178539906665e-16, `time`: 0.1041s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.858682624383165e-16, `time`: 0.0926s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.66769808831266e-16, `time`: 0.0966s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.803312206174027e-16, `time`: 0.0928s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.615772601481742e-16, `time`: 0.0950s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.584662057028017e-16, `time`: 0.0941s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.055676025949996e-16, `time`: 0.0973s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.7359382556054013e-16, `time`: 0.0923s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.588839367661881e-16, `time`: 0.0904s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.6119363698442235e-16, `time`: 0.0970s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.642252441126063e-16, `time`: 0.0973s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.6122519268499847e-16, `time`: 0.0984s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.439035479131772e-16, `time`: 0.0980s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.6300493375008597e-16, `time`: 0.0967s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.842851015499487e-16, `time`: 0.0948s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.4385426197507178e-15, `time`: 0.0943s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.5277074619379526e-16, `time`: 0.0925s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.72622724370135e-16, `time`: 0.0967s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.131302272090627e-16, `time`: 0.0965s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.882924245147972e-16, `time`: 0.0988s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.034899569643717e-16, `time`: 0.0948s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.4415017702429945e-15, `time`: 0.0976s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.5453186911528167e-16, `time`: 0.0957s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.1463283967517028e-15, `time`: 0.0954s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.875442497339073e-16, `time`: 0.1131s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.461708227212347e-15, `time`: 0.0961s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.827250584908722e-16, `time`: 0.0956s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.037220276211633e-16, `time`: 0.1065s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.603774580562679e-16, `time`: 0.0928s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 9.197509290268762e-16, `time`: 0.0962s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.815175432542733e-16, `time`: 0.0933s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.0219775886962963e-15, `time`: 0.0942s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.784408829135567e-17, `time`: 0.0940s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.7026559018273678e-16, `time`: 0.0984s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.908693181283116e-16, `time`: 0.0935s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.148045281866041e-16, `time`: 0.0946s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.794623719369642e-16, `time`: 0.0936s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 2.670354218124834e-16, `time`: 0.0964s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.0747426555069834e-16, `time`: 0.0979s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.863888457568574e-16, `time`: 0.0956s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.61645076767304e-16, `time`: 0.0930s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.183504332054233e-16, `time`: 0.0974s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 8.011492970993124e-16, `time`: 0.0966s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.061956698795708e-15, `time`: 0.0982s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 3.815647944112575e-16, `time`: 0.0990s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.682305421758012e-16, `time`: 0.0947s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 6.344174535897343e-16, `time`: 0.0933s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 7.731020137878353e-16, `time`: 0.0912s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 5.576156618131575e-16, `time`: 0.0941s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 4.583146880650312e-16, `time`: 0.0911s
SUCCESS: `func_tol` reached after 7 iterations (levenberg_marquardt), `f_val`: 1.1555761956227004e-16, `time`: 0.0938s

In [14]:
# create 30Y liability position 
lby_pos = LiabilityPosition(
  pos_id = 'liabilities 30Y', 
  pos_grp = 'liabilities', 
  currency = 'eur',   
  effective_dt = curve_date, 
  payment_schedule = liabilities_payment_schedule, 
  position_curve_builder = curve 
)

In [17]:
# create an instance of LiabilityHedgeConstructor - the object which generates hedges for the liability position 
lby_hedge = LiabilityHedgeConstructor(
  liability_position = lby_pos, 
  liability_curve = curve, 
  liquid_irs_tenors = ['2Y','5Y','10Y','30Y'], # this argument specifies tenors which are considered as liquid and are used to construct a proxy hedge
  swap_rate_cov_mat = scenarios.hist_cov_mat, 
  hedge_dt = curve_date )

In [18]:
# create hedged portfolio - with full benchmark hedge 
lby_prtfl_full_hedge = lby_hedge.create_hedged_portfolio(
    liability_position = lby_hedge.liability_position, 
    hedge_positions = lby_hedge.benchmark_hedge_positions, 
    effective_dt = curve_date, 
    prtfl_id = 'liabilities 30Y (benchmark hedge)' )

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(

SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0059s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0044s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0043s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(

SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0066s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0060s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0043s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0041s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0048s

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(

SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0089s

In [19]:
# create hedged portfolio - with proxy hedge 
lby_prtfl_proxy_hedge = lby_hedge.create_hedged_portfolio(
    liability_position = lby_hedge.liability_position, 
    hedge_positions = lby_hedge.liquid_proxy_hedge_positions, 
    effective_dt = curve_date, 
    prtfl_id = 'liabilities 30Y (proxy hedge)' )

C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(
C:\Users\mduba\Desktop\Programming\Python\alm_ir_hedging_prototype\.venv\Lib\site-packages\rateslib\curves\curves.py:275: UserWarning: Evaluating points on a curve beyond the endpoint of the basic spline interval is undefined.
date: 2056-04-07, spline end: 2056-04-05, curve id: 'eurswap_solver'
This often occurs when a curve is constructed with a final node date that aligns with the maturity of an instrument with a payment lag.
In the case that the instrument has a payment lag (e.g. a SOFR swap or ESTR swap or bond terminating on a non-business day) then a cashflow will occur after the maturity of the instrument.
The solution is to ensure that the final node date of the curve is changed to be beyond that expected payment date.
  warnings.warn(

SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0040s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s
SUCCESS: `func_tol` reached after 0 iterations (levenberg_marquardt), `f_val`: 0.0, `time`: 0.0039s

In [20]:
# portfolio positions and risk sens.
lby_prtfl_proxy_hedge.positions
lby_prtfl_full_hedge.positions
  
lby_prtfl_proxy_hedge.spot_delta
lby_prtfl_full_hedge.spot_delta  

lby_prtfl_proxy_hedge.spot_delta
lby_prtfl_full_hedge.spot_delta  

lby_prtfl_proxy_hedge.fwd_delta
lby_prtfl_full_hedge.fwd_delta  

lby_prtfl_proxy_hedge.spot_gamma
lby_prtfl_full_hedge.spot_gamma

,Date,Portfolio ID,Position Grp,Position ID,Sensitivity,Ccy,Curve,Total,2Y,3Y,5Y,7Y,10Y,12Y,15Y,20Y,25Y,30Y
0,2026-03-31,liabilities 30Y (benchmark hedge),liabilities,liabilities 30Y,Gamma,EUR,eurswap,-23594.033721,-142.889546,-185.621546,-418.390574,-906.97869,-1390.806697,-1097.446135,-3803.580942,-5927.500489,-6972.118421,-2748.700681
1,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 2Y ATM Payer @ 2.948%,Gamma,EUR,eurswap,-2.293829,-2.624368,0.38097,-0.06918,0.022955,-0.006553,0.002768,-0.000494,0.000098,-0.000031,0.000006
2,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 3Y ATM Receiver @ 2.934%,Gamma,EUR,eurswap,3.522969,1.12807,2.354237,0.055798,-0.018538,0.005303,-0.002243,0.000401,-0.00008,0.000025,-0.000005
3,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 5Y ATM Receiver @ 2.983%,Gamma,EUR,eurswap,10.359006,1.116888,1.489399,7.971693,-0.268212,0.076775,-0.032494,0.00582,-0.001158,0.000369,-0.000074
4,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 7Y ATM Receiver @ 3.036%,Gamma,EUR,eurswap,114.957352,6.815838,7.547314,22.825141,78.59453,-1.28538,0.542322,-0.096666,0.019085,-0.006039,0.001206
5,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 10Y ATM Receiver @ 3.11%,Gamma,EUR,eurswap,356.829803,10.083257,12.94102,28.586123,62.399801,253.748062,-12.891589,2.303887,-0.456749,0.145047,-0.029056
6,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 12Y ATM Receiver @ 3.195%,Gamma,EUR,eurswap,329.148219,6.447915,8.164769,18.588572,38.453233,60.128028,197.868196,-0.589318,0.116232,-0.036744,0.007336
7,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 15Y ATM Receiver @ 3.244%,Gamma,EUR,eurswap,2302.566594,28.343503,36.279775,80.487506,174.433141,228.558065,313.494197,1455.695171,-19.756584,6.296404,-1.264584
8,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 20Y ATM Receiver @ 3.246%,Gamma,EUR,eurswap,5794.935334,38.688628,48.923598,111.370281,230.601959,359.457999,257.673387,1010.197829,3838.815367,-126.147856,25.35414
9,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 25Y ATM Receiver @ 3.186%,Gamma,EUR,eurswap,9715.926267,39.543163,50.109425,113.274597,237.617342,353.304605,313.159454,906.964445,1723.127962,6069.567768,-90.742495
10,2026-03-31,liabilities 30Y (benchmark hedge),Benchmark IRS Hedge,EURIBOR6M 30Y ATM Receiver @ 3.115%,Gamma,EUR,eurswap,4978.650429,13.345793,16.874198,38.256677,79.853352,120.923508,99.519697,321.158266,519.284766,815.500209,2953.933962
11,2026-03-31,liabilities 30Y (benchmark hedge),,Total,Gamma,EUR,eurswap,10.568423,-0.000859,-0.556839,2.956635,-5.289127,-15.896287,71.887561,-107.941602,133.648452,-206.799267,138.559757

In [21]:
# simulate mc pnl for hedged portfolios - with 1000 scenarios - takes approx. 8 mins for 2 portfolio
print("start at: ", datetime.now())
lby_prtfl_proxy_hedge.simulate_pnl(mc_curve_scenarios = scenarios)
lby_prtfl_full_hedge.simulate_pnl(mc_curve_scenarios = scenarios)
print("end at: ", datetime.now())

start at:  2026-05-05 20:39:40.101711
end at:  2026-05-05 20:44:13.891218

In [23]:
# CVaR for all portfolios  
lby_prtfl_proxy_hedge.calc_cvar(0.95)
lby_prtfl_full_hedge.calc_cvar(0.95)
  
lby_prtfl_proxy_hedge.prtfl_cvar
lby_prtfl_full_hedge.prtfl_cvar
  
lby_prtfl_proxy_hedge.pos_grp_cvar
lby_prtfl_full_hedge.pos_grp_cvar
    
lby_prtfl_proxy_hedge.pos_cvar
lby_prtfl_full_hedge.pos_cvar  
  
lby_prtfl_proxy_hedge.pv01_delta_cvar_attr
lby_prtfl_full_hedge.pv01_delta_cvar_attr

lby_prtfl_proxy_hedge.sim_pos_pnl
lby_prtfl_full_hedge.sim_pos_pnl

lby_prtfl_proxy_hedge.sim_pos_grp_pnl
lby_prtfl_full_hedge.sim_pos_grp_pnl

lby_prtfl_proxy_hedge.sim_prtfl_pnl
lby_prtfl_full_hedge.sim_prtfl_pnl

,Date,Portfolio ID,Time Horizon (Days),Ccy,Curve,Scenario,PnL
0,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,1,7127.534113
1,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,2,16709.442240
2,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,3,9013.384295
3,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,4,24338.410921
4,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,5,7996.496772
...,...,...,...,...,...,...,...
995,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,996,40944.185321
996,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,997,502458.870232
997,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,998,127216.572892
998,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,999,13069.120325
999,2026-03-31,liabilities 30Y (benchmark hedge),30,EUR,eurswap,1000,222611.641099